# Dependencies
pygments:     true

# Permalinks
permalink:    pretty

# Pagination
paginate:     5

# Meta data
title:        ws1
author:       "Zlatan Vasović"
description:  "Official ws1 site and blog."
keywords:     "ws1, github, design, programming"
url:          "http://ws1.github.io"
language:     en

# Links and social networks
twitter:      webserveri
github:       ws1